import java.awt.AWTException;
import java.awt.Color;
import java.awt.Robot;
import java.awt.Point;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leon
 */
public class shortcutJDialog extends javax.swing.JDialog {

    myJFrame myParent;
    Robot bot;
    boolean firstInSentence;
    
    private javax.swing.JTextArea myArea = null;
    
    private javax.swing.JButton buttnA = null;
    private javax.swing.JButton buttnB = null;
    private javax.swing.JButton buttnC = null;
    private javax.swing.JButton buttnD = null;
    private javax.swing.JButton buttnE = null;
    private javax.swing.JButton buttnF = null;
    private javax.swing.JButton buttnG = null;
    private javax.swing.JButton buttnH = null;
    private javax.swing.JButton buttnI = null;
    private javax.swing.JButton buttnJ = null;
    private javax.swing.JButton buttnK = null;
    private javax.swing.JButton buttnL = null;
    private javax.swing.JButton buttnM = null;
    private javax.swing.JButton buttnN = null;
    private javax.swing.JButton buttnO = null;
    private javax.swing.JButton buttnP = null;
    private javax.swing.JButton buttnQ = null;
    private javax.swing.JButton buttnR = null;
    private javax.swing.JButton buttnS = null;
    private javax.swing.JButton buttnT = null;
    private javax.swing.JButton buttnU = null;
    private javax.swing.JButton buttnV = null;
    private javax.swing.JButton buttnW = null;
    private javax.swing.JButton buttnX = null;
    private javax.swing.JButton buttnY = null;
    private javax.swing.JButton buttnZ = null;
    
    String LetterTop;
    String LetterTopLeft;
    String LetterTopRight;
    String LetterMiddle;
    String LetterLeft;
    String LetterRight;
    String LetterBottom = " ";
    String LetterBottomLeft;
    String LetterBottomRight;
    
    /**
     * Creates new form shortcutJDialog
     */
    public shortcutJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    public shortcutJDialog() {
        initComponents();
    }
    
    public shortcutJDialog(String letter, javax.swing.JTextArea area) {
        myArea = area;
        initComponents();
    }
    
    public shortcutJDialog(myJFrame parent, javax.swing.JTextArea area,
            javax.swing.JButton btnA,
            javax.swing.JButton btnB,
            javax.swing.JButton btnC,
            javax.swing.JButton btnD,
            javax.swing.JButton btnE,
            javax.swing.JButton btnF,
            javax.swing.JButton btnG,
            javax.swing.JButton btnH,
            javax.swing.JButton btnI,
            javax.swing.JButton btnJ,
            javax.swing.JButton btnK,
            javax.swing.JButton btnL,
            javax.swing.JButton btnM,
            javax.swing.JButton btnN,
            javax.swing.JButton btnO,
            javax.swing.JButton btnP,
            javax.swing.JButton btnQ,
            javax.swing.JButton btnR,
            javax.swing.JButton btnS,
            javax.swing.JButton btnT,
            javax.swing.JButton btnU,
            javax.swing.JButton btnV,
            javax.swing.JButton btnW,
            javax.swing.JButton btnX,
            javax.swing.JButton btnY,
            javax.swing.JButton btnZ) throws AWTException {
        bot = new Robot();
        
        initComponents();
        myParent = parent;
        myArea = area;
        
        buttnA = btnA;
        buttnB = btnB;
        buttnC = btnC;
        buttnD = btnD;
        buttnE = btnE;
        buttnF = btnF;
        buttnG = btnG;
        buttnH = btnH;
        buttnI = btnI;
        buttnJ = btnJ;
        buttnK = btnK;
        buttnL = btnL;
        buttnM = btnM;
        buttnN = btnN;
        buttnO = btnO;
        buttnP = btnP;
        buttnQ = btnQ;
        buttnR = btnR;
        buttnS = btnS;
        buttnT = btnT;
        buttnU = btnU;
        buttnV = btnV;
        buttnW = btnW;
        buttnX = btnX;
        buttnY = btnY;
        buttnZ = btnZ;
        colorOff();
 //       this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLayeredPane1 = new javax.swing.JLayeredPane();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        formMouseReleased(evt);
      }
    });

    jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonTopLeftActionPerformed(evt);
      }
    });

    jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton2.setText("jButton1");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonTopActionPerformed(evt);
      }
    });

    jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton3.setText("jButton1");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonTopRightActionPerformed(evt);
      }
    });

    jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton4.setText("jButton1");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRightActionPerformed(evt);
      }
    });

    jButton6.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton6.setText("jButton1");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonMiddleActionPerformed(evt);
      }
    });

    jButton7.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton7.setText("jButton1");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonBottomActionPerformed(evt);
      }
    });

    jButton8.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton8.setText("jButton1");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLeftActionPerformed(evt);
      }
    });

    jButton9.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton9.setText("jButton1");
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonBottomLeftActionPerformed(evt);
      }
    });

    jButton5.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
    jButton5.setText("jButton1");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonBottomRightActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addGap(1, 1, 1)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(4, 4, 4)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(4, 4, 4)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1))))
    );
    jLayeredPane1Layout.setVerticalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(4, 4, 4)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(4, 4, 4)
        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(1, 1, 1)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterTop);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterTop);
        }
        setVisible(false);
        updateBox(LetterTop.charAt(0));
    }//GEN-LAST:event_jButtonTopActionPerformed

    private void jButtonMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiddleActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterMiddle);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterMiddle);
        }
        setVisible(false);
        updateBox(LetterMiddle.charAt(0));
    }//GEN-LAST:event_jButtonMiddleActionPerformed

    private void jButtonTopLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopLeftActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterTopLeft);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterTopLeft);
        }
        setVisible(false);
        updateBox(LetterTopLeft.charAt(0));
    }//GEN-LAST:event_jButtonTopLeftActionPerformed

    private void jButtonTopRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopRightActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterTopRight);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterTopRight);
        }
        setVisible(false);
        updateBox(LetterTopRight.charAt(0));
    }//GEN-LAST:event_jButtonTopRightActionPerformed

    private void jButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterRight);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterRight);
        }
        setVisible(false);
        updateBox(LetterRight.charAt(0));
    }//GEN-LAST:event_jButtonRightActionPerformed

    private void jButtonBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBottomActionPerformed
        if (LetterBottom.equals("m")) {
            myArea.append("m");
            setVisible(false);
            updateBox('m');
            return;
        }
        if (LetterBottom.equals(".")) {
            String str = myArea.getText();
            int len = str.length();
            if (len > 0) {
                myArea.setText(str.substring(0, len-1));
            }
            else
                myArea.setText("");
            myArea.append(". ");
            setVisible(false);
            firstInSentence = true;
            updateBox(' ');
            return;
        }
        if (LetterBottom.equals(" ")) {
            if (myArea != null) {
                if(myParent.mode == myJFrame.Mode.COMPLETION) {
                    int pos = myArea.getSelectionEnd();
                    myArea.insert(" ", pos);
                    myArea.setCaretPosition(pos + 1);
                    myParent.mode = myJFrame.Mode.INSERT;
                    colorOff();
                }
                else
                    myArea.append(LetterBottom);
            }
            setVisible(false);
            firstInSentence = false;
            updateBox(' ');
            return;
        }
        
        
    }//GEN-LAST:event_jButtonBottomActionPerformed

    private void jButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterLeft);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterLeft);
        }
        setVisible(false);
        updateBox(LetterLeft.charAt(0));
    }//GEN-LAST:event_jButtonLeftActionPerformed

    private void jButtonBottomLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBottomLeftActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterBottomLeft);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterBottomLeft);
        }
        setVisible(false);
        updateBox(LetterBottomLeft.charAt(0));
    }//GEN-LAST:event_jButtonBottomLeftActionPerformed

    private void jButtonBottomRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBottomRightActionPerformed
        if (myArea != null) {
            if(myParent.mode == myJFrame.Mode.COMPLETION) {
                myArea.replaceSelection(LetterBottomRight);
                myParent.mode = myJFrame.Mode.INSERT;
                colorOff();
            }
            else
                myArea.append(LetterBottomRight);
        }
        setVisible(false);
        updateBox(LetterBottomRight.charAt(0));
    }//GEN-LAST:event_jButtonBottomRightActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
    }//GEN-LAST:event_formMouseReleased

    public void colorOn(){
        jButton7.setBackground(Color.yellow);
    }
    
    public void colorOff(){
        jButton7.setBackground(Color.gray);
    }
    
    public void updateBox(char ltr) {
        Point p;
        setVisible(true);
        switch(ltr){
            case 'a':
                setLocationRelativeTo(buttnA);
                p = buttnA.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "a";
                LetterTop =         "d";
                LetterLeft =        "r";
                LetterRight =       "c";
                LetterBottomLeft =  "n";
                LetterBottomRight = "l";
                LetterTopLeft =     "t";
                LetterTopRight =    "s";
                LetterBottom =      " ";
                jButton6.setText("a"); //m
                jButton2.setText("d"); //t
                jButton8.setText("r"); //l
                jButton4.setText("c"); //r
                jButton9.setText("n"); //bl
                jButton5.setText("l"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("s"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'b':
                setLocationRelativeTo(buttnB);
                p = buttnB.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "b";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "y";
                LetterBottomRight = "r";
                LetterTopLeft =     "l";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("b"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("y"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("l"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'c':
                setLocationRelativeTo(buttnC);
                p = buttnC.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "c";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "h";
                LetterBottomLeft =  "i";
                LetterBottomRight = "h";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("c"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("h"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'd':
                setLocationRelativeTo(buttnD);
                p = buttnD.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "d";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "r";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("d"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("r"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'e':
                setLocationRelativeTo(buttnE);
                p = buttnE.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "e";
                LetterTop =         "d";
                LetterLeft =        "r";
                LetterRight =       "a";
                LetterBottomLeft =  "n";
                LetterBottomRight = "l";
                LetterTopLeft =     "c";
                LetterTopRight =    "s";
                LetterBottom =      " ";
                jButton6.setText("e"); //m
                jButton2.setText("d"); //t
                jButton8.setText("r"); //l
                jButton4.setText("a"); //r
                jButton9.setText("n"); //bl
                jButton5.setText("l"); //br
                jButton1.setText("c"); //tl
                jButton3.setText("s"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'f':
                setLocationRelativeTo(buttnF);
                p = buttnF.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "f";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("f"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'g':
                setLocationRelativeTo(buttnG);
                p = buttnG.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "g";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "h";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("g"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("h"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'h':
                setLocationRelativeTo(buttnH);
                p = buttnH.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "h";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("h"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'i':
                setLocationRelativeTo(buttnI);
                p = buttnI.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "i";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "c";
                LetterBottomLeft =  "n";
                LetterBottomRight = "l";
                LetterTopLeft =     "t";
                LetterTopRight =    "s";
                LetterBottom =      " ";
                jButton6.setText("i"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("c"); //r
                jButton9.setText("n"); //bl
                jButton5.setText("l"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("s"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'j':
                setLocationRelativeTo(buttnJ);
                p = buttnJ.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "j";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "p";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("j"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("p"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'k':
                setLocationRelativeTo(buttnK);
                p = buttnK.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "k";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "n";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "l";
                LetterTopRight =    "y";
                LetterBottom =      " ";
                jButton6.setText("k"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("n"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("l"); //tl
                jButton3.setText("y"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'l':
                setLocationRelativeTo(buttnL);
                p = buttnL.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "l";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "d";
                LetterTopRight =    "y";
                LetterBottom =      " ";
                jButton6.setText("l"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("d"); //tl
                jButton3.setText("y"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'm':
                setLocationRelativeTo(buttnM);
                p = buttnM.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "m";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "p";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("m"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("p"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'n':
                setLocationRelativeTo(buttnN);
                p = buttnN.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "n";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "g";
                LetterBottomLeft =  "d";
                LetterBottomRight = "s";
                LetterTopLeft =     "t";
                LetterTopRight =    "c";
                LetterBottom =      " ";
                jButton6.setText("n"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("g"); //r
                jButton9.setText("d"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("c"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'o':
                setLocationRelativeTo(buttnO);
                p = buttnO.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "o";
                LetterTop =         "m";
                LetterLeft =        "r";
                LetterRight =       "f";
                LetterBottomLeft =  "n";
                LetterBottomRight = "l";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("o"); //m
                jButton2.setText("m"); //t
                jButton8.setText("r"); //l
                jButton4.setText("f"); //r
                jButton9.setText("n"); //bl
                jButton5.setText("l"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'p':
                setLocationRelativeTo(buttnP);
                p = buttnP.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "p";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "t";
                LetterTopRight =    "l";
                LetterBottom =      " ";
                jButton6.setText("p"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("l"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'q':
                setLocationRelativeTo(buttnQ);
                p = buttnQ.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "q";
                LetterTop =         "n";
                LetterLeft =        "l";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "r";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("q"); //m
                jButton2.setText("n"); //t
                jButton8.setText("l"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("r"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'r':
                setLocationRelativeTo(buttnR);
                p = buttnR.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "r";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "t";
                LetterTopRight =    "y";
                LetterBottom =      " ";
                jButton6.setText("r"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("y"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 's':
                setLocationRelativeTo(buttnS);
                p = buttnS.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "s";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "h";
                LetterTopLeft =     "t";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("s"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("h"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 't':
                setLocationRelativeTo(buttnT);
                p = buttnT.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "t";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "h";
                LetterTopRight =    "r";
                LetterBottom =      " ";
                jButton6.setText("t"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("h"); //tl
                jButton3.setText("r"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'u':
                setLocationRelativeTo(buttnU);
                p = buttnU.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "u";
                LetterTop =         "e";
                LetterLeft =        "r";
                LetterRight =       "c";
                LetterBottomLeft =  "n";
                LetterBottomRight = "l";
                LetterTopLeft =     "t";
                LetterTopRight =    "s";
                LetterBottom =      " ";
                jButton6.setText("u"); //m
                jButton2.setText("e"); //t
                jButton8.setText("r"); //l
                jButton4.setText("c"); //r
                jButton9.setText("n"); //bl
                jButton5.setText("l"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("s"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'v':
                setLocationRelativeTo(buttnV);
                p = buttnV.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "v";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "y";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("v"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("y"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'w':
                setLocationRelativeTo(buttnW);
                p = buttnW.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "w";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "h";
                LetterTopRight =    "n";
                LetterBottom =      " ";
                jButton6.setText("w"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("h"); //tl
                jButton3.setText("n"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'x':
                setLocationRelativeTo(buttnX);
                p = buttnX.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "x";
                LetterTop =         "e";
                LetterLeft =        "c";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "t";
                LetterTopLeft =     "p";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("x"); //m
                jButton2.setText("e"); //t
                jButton8.setText("c"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("t"); //br
                jButton1.setText("p"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'y':
                setLocationRelativeTo(buttnY);
                p = buttnY.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "y";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "p";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "t";
                LetterTopRight =    "m";
                LetterBottom =      " ";
                jButton6.setText("y"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("p"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("t"); //tl
                jButton3.setText("m"); //tr
                jButton7.setText("cmt"); //b
                break;
            case 'z':
                setLocationRelativeTo(buttnZ);
                p = buttnZ.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "z";
                LetterTop =         "e";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "y";
                LetterTopLeft =     "c";
                LetterTopRight =    "u";
                LetterBottom =      " ";
                jButton6.setText("z"); //m
                jButton2.setText("e"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("y"); //br
                jButton1.setText("c"); //tl
                jButton3.setText("u"); //tr
                jButton7.setText("cmt"); //b
                break;
            case ' ':
                setLocationRelativeTo(buttnB);
                p = buttnB.getLocationOnScreen();
                bot.mouseMove(p.x+28, p.y+35);
                LetterMiddle =      "b";
                LetterTop =         "w";
                LetterLeft =        "o";
                LetterRight =       "a";
                LetterBottomLeft =  "i";
                LetterBottomRight = "s";
                LetterTopLeft =     "h";
                LetterTopRight =    "t";
                if (firstInSentence)
                    LetterBottom =      "m";
                else
                    LetterBottom =      ".";
                jButton6.setText("b"); //m
                jButton2.setText("w"); //t
                jButton8.setText("o"); //l
                jButton4.setText("a"); //r
                jButton9.setText("i"); //bl
                jButton5.setText("s"); //br
                jButton1.setText("h"); //tl
                jButton3.setText("t"); //tr
                if (firstInSentence)
                    jButton7.setText("m"); //b
                else
                    jButton7.setText("."); //b
                break;
            default:
                break;           
        }
                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shortcutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shortcutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shortcutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shortcutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                shortcutJDialog dialog = new shortcutJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLayeredPane jLayeredPane1;
  // End of variables declaration//GEN-END:variables
}
